### ISSUE TITLE
Can I contribute? 

### ISSUE THREAD

**Issue by zionitcorp** [maurodelazeri/forexcalendar#2]
Hi Mauro,

I have fixed an issue in the original code for the currency field having a \n at the beginning and the end. Also, I included the column "impact" for the high, medium, low options. Everything is tested and working. Can I be allowed to make Pull Requests? 

Thanks and congratulations for the so simple and effective code for Forex Calendar scrap. I loved it! 

Rgds,

Alex.

**Comment by maurodelazeri** [comment]
Hey @zionitcorp thanks, this is something I did long time ago, the pull  request is more than welcome

**Comment by zionitcorp** [comment]
Should I have access to create a new branch in order to commit my changes before the pull request?

**Comment by zionitcorp** [comment]
Just in case, I pulled the changes to my fork rep. and you can see it here: https://github.com/zionitcorp/forexcalendar/commit/906b7b457a1d46614e59e02fcf674905f33bc27d.
Again, this was a very elegant piece of code being very useful to me right now. Thanks for providing it!
